## Why use Numpy? It's way faster than Python lists 

In [8]:
# zip() in python
# zip() takes two iterables and combine them element by element in pairs (or tuples).
l1 = [1,2,3,4]
l2 = [6,7,8,9]
list(zip(l1,l2))


[(1, 6), (2, 7), (3, 8), (4, 9)]

In [9]:
# speed test of lists execution in python
import numpy as np
import time

size = 1_000_000_0
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
addition = [x + y for x,y in zip(list1, list2)]    
end = time.time()
print(addition[0:100])
print(f"Speed: {(end) - (start)}")

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
Speed: 1.7126858234405518


In [10]:
# speed test of arrays execution in Numpy
import numpy as np
import time

size = 1_000_000_0

list1 = np.array(list(range(size)))
list2 = np.array(list(range(size)))

start = time.time()
addition = list1 + list2
end = time.time()
print(addition[0:100])
print(f"Speed: {(end) - (start)}")

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
Speed: 0.21931028366088867


## Creating Numpy Arrays

In [11]:
import numpy as np

# creating a 1D Numpy array
arr1 = np.array([1,2,3,4,5])
print(f"One dimensional array: {arr1}")

# creatng a 2D Numpy Array
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print(f"Two dimensional array: {arr2}")

# checking type and shape
print(f"Type: {type(arr1)}")
print(f"Shape: {arr2.shape}")

One dimensional array: [1 2 3 4 5]
Two dimensional array: [[1 2 3 4]
 [5 6 7 8]]
Type: <class 'numpy.ndarray'>
Shape: (2, 4)


## Memory efficiency Numpy vs Lists

In [12]:
import numpy as np
import sys

list_data = list(range(1_000))
numpy_data = np.array(list_data)

print(f"Python list size: {sys.getsizeof(list_data) * len(list_data)} bytes.")
print(f"Numpy array size: {numpy_data.nbytes} bytes.")

# Numpy arrays use significantly less memory compared to python lists..

Python list size: 8056000 bytes.
Numpy array size: 8000 bytes.


## Vectorization --> No More Loops

In [13]:
import numpy as np

# In python way
numbers = [1,2,3,4,5]
doubled = [x * 2 for x in numbers]
print(doubled)

# Numpy vectorized way
arr = np.array([1,2,3,4,5])
doubled = arr * 2
print(doubled)

# ............................

# adding two lists/array

# python way
a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = [x+y for x,y in zip(a,b)]
print(c)

# Numpy vectorized way
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1 + arr2)

# add 10 to every number using Numpy vectorization
addition = arr1 + 10
print(addition)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
[7, 9, 11, 13, 15]
[ 7  9 11 13 15]
[11 12 13 14 15]


## Numpy vectorization speed test Lists/array

In [14]:
import numpy as np
import time
# In python way
a = list(range(1_000_000))
start = time.time()
b = [x**2 for x in a]
end = time.time()
print(f"Speed: {(end) - (start):.5f} seconds")

# In Numpy vectorization
arr = np.arange(1_000_000)
start = time.time()
ans = arr ** 2
end = time.time()
print(f"Speed: {(end) - (start):.5f} seconds")

Speed: 0.24242 seconds
Speed: 0.00474 seconds


##        Conclusion
######  - NumPy is faster tha Python lists because it is optimized in C.
######  - NumPy consumes less memory due to efficient storage.
######  - NumPy provides vectorized operations.
######  - NumPy is essential for data science and machine learning.