## Methods to create arrays

###### 1. np.array()

In [1]:
# Convert Python list/tuple into a Numpy array
import numpy as np
arr1 = np.array([1,2,3,4,5])  # from list
arr2 = np.array((1,2,3,4,5))  # from tuple

print(arr1)
print(arr1)
# when we already have Python data and just want it in NumPy form.

[1 2 3 4 5]
[1 2 3 4 5]


###### 2. np.arange(start, stop, step)

In [2]:
arr = np.arange(1,10,2)
print(arr)
# when we want a range of numbers with fixed steps.

[1 3 5 7 9]


###### 3. np.linspace(start, stop, num)

In [3]:
arr = np.linspace(1,100,5)
print(arr)
# when we want fractions/decimal steps, not just integers.

[  1.    25.75  50.5   75.25 100.  ]


###### 4. np.zeros(shape)

In [4]:
# Array filled with zeros.
arr = np.zeros((2,3))
print(arr)
# Useful for initializing arrays before filling with values.

[[0. 0. 0.]
 [0. 0. 0.]]


###### 5. np.ones(shape)

In [5]:
# Array filled with ones.
arr = np.ones((3,4))
print(arr)
# Similar to zeros, but with ones.

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


###### 6. np.full(shape, fill_value)

In [6]:
arr = np.full((2,3), 7)
print(arr)

[[7 7 7]
 [7 7 7]]


###### 7. np.empty(shape)

In [7]:
# Creates an array without setting values (random garbage inside)
arr = np.empty((2,3))
print(arr)
# values are unpredictable.

[[0. 0. 0.]
 [0. 0. 0.]]


###### 8. np.identity(n)

In [8]:
# Creates a square identity matrix (1s on diagonal).
arr = np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Checking Array Properties

In [9]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

###### 1. .ndim → Number of Dimensions

In [10]:
print(arr.ndim)

2


###### 2. .shape → Shape (dimensions)

In [11]:
print(arr.shape)

(4, 3)


###### 3. .size → Total Number of Elements

In [12]:
print(arr.size)

12


###### 4. .dtype → Data Type of Elements

In [13]:
print(arr.dtype)

int64


###### 5. .nbytes → Total Memory Used

In [14]:
arr.nbytes

96

###### 6. .T → Transpose (rows ↔ columns)

In [15]:
arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## Changing Data Types

In [25]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6.1,7.2,8.3,9.4])
print(arr1)
print(arr2)
print(f"Type of {arr1} is: {arr1.dtype}")
print(f"Type of {arr2} is: {arr2.dtype}")
# dtype means data type of an array

[1 2 3 4 5]
[6.1 7.2 8.3 9.4]
Type of [1 2 3 4 5] is: int64
Type of [6.1 7.2 8.3 9.4] is: float64


###### 1. Convert float → int

In [26]:
converted = arr2.astype(int)
print(converted)
print(converted.dtype)


[6 7 8 9]
int64


###### 2. Convert int → float

In [27]:
new_arr = arr1.astype(float)
print(new_arr)
print(new_arr.dtype)

[1. 2. 3. 4. 5.]
float64


###### 3. Convert numbers → string

In [28]:
new_arr = arr1.astype(str)
print(new_arr)
print(new_arr.dtype)   

['1' '2' '3' '4' '5']
<U21


###### 4. Convert string numbers → int

In [29]:
arr = np.array(['1','2','3','4','5'])
new_arr = arr.astype(int)
print(arr)
print(new_arr)
print(new_arr.dtype)

['1' '2' '3' '4' '5']
[1 2 3 4 5]
int64


###### 5. np.array() with dtype parameter

In [30]:
arr = np.array([1.2,2.2,3.3,4.5], dtype= int)
print(arr.dtype)


int64


## Reshaping and Flattening Array

In [31]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr.dtype)
print(arr.ndim)

int64
2


###### 1. Reshaping(d)

In [32]:
new_arr = arr.reshape((4, 3))
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##### 2. Flattening

In [33]:
# Turns any multi-dimensional array into 1D.
flat = arr.flatten()
print(flat)
print(flat.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
