## Indexing and Slicing (Same as Python Lists)

###### 1. Basic Indexing & Slicing (1D Array)

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])  # --> 1D

# Indexing........
print(arr[0])    # first element
print(arr[-1])   # last element
print(arr[2])    # 2nd element

# Slicing..........
print(arr[1:3])  # slice from 1 to 3
print(arr[:])    # all
print(arr[:-1])  # slice from 0 to second last


10
50
30
[20 30]
[10 20 30 40 50]
[10 20 30 40]


###### 2. Indexing in 2D Arrays

In [2]:
arr = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16] ])  # --> 2D

# Indexing........
print(arr[0,0])     # (row 0, col 0)
print(arr[3, -1])   # (row 3, col last)

# Slicing..........
print(arr[0, :])     # (row 0, col all)
print(arr[2, 1:3])   # (row 2, col 1 to 3)
print(arr[0:3, 1:3]) # (row 0 to 3, from these rows -> col 1 to 3)
print(arr[1:3, 3])   # (from row 1 and 2, col 3)

1
16
[1 2 3 4]
[10 11]
[[ 2  3]
 [ 6  7]
 [10 11]]
[ 8 12]


###### 3. Extracting Rows and Columns

In [3]:
arr = np.array([ [1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [30,40,50,60] ])  # --> 2D

print(arr[0, :])    # first row --> [1,2,3,4]
print(arr[1, :])    # second row --> [5,6,7,8]

print(arr[:, 1])    # second col --> [2,6,10,40]
print(arr[:, 3])    # third col  --> [4,8,12,60]

[1 2 3 4]
[5 6 7 8]
[ 2  6 10 40]
[ 4  8 12 60]


In [4]:
# Slicing.......
arr = np.array([10,20,30,40,50,60])

sliced = arr[1:4]
sliced[2] = 90
print(arr)   # In Python list slicing returns a copy, But In NumPy array it returns a view, not a copy,
                                                                     # (In NumPy changes affect the original array)



[10 20 30 90 50 60]


## Fancy Indexing

In [5]:
arr = np.array([10,20,30,40,50,60])

print(arr[[1,2,3]])    # multi indexing


idx = [4,5]
print(arr[idx])

[20 30 40]
[50 60]


## Boolean Indexing

In [6]:
arr = np.array([10,20,30,40,50,60])

mask = arr > 25
print(mask)
print(arr[mask])

# find even numbers...........
ar = np.array([1,2,3,4,5,6,7,8])

even = ar %2==0
print(even)
print(ar[even])

[False False  True  True  True  True]
[30 40 50 60]
[False  True False  True False  True False  True]
[2 4 6 8]
