## Multidimensional Indexing & Axis

In [5]:
# Axes ... ?????

# Axis 0 --> Rows direction (downwards)
# Axis 1 --> Columns direction (across)
# Axis 2 --> Depth (for 3D arrys,like image channels)
# .......................................................................

# for 2D (matrix)

import numpy as np
# ---> 2D
arr = np.array([[10,20,30],
               [40,50,60],
                [70,80,90]
               ])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
# axis 0 (down): goes through rows (top --> bottom)
# axis 1 (across): goes through colums (left --> right)
# ............................
#  In short:::
#           # axis 0 --> work down the rows --> column-wise result
#           # axis 1 --> work across the columns --> row-wise result

print(arr.sum(axis=0))    # Sum along axis 0 (down the rows ---> column sums)
print(arr.sum(axis=1))    # Sum along axis 1 (across columns ---> row sums)

[12 15 18]
[ 6 15 24]


In [26]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

# print(arr[0])   # first row
# print(arr[1])   # second row

# for specific element............
# print(arr[0, 2])    # row 1 ---> column 2
# print(arr[0:2])     # row 1 and 2
print(arr[0:2, 0:2])  # row 1 and 2, column 1 and 2 from each row

[[1 2]
 [4 5]]


## Indexing in 3D Arrays

In [52]:
# axis 0 --> operates throughh blocks 
# axis 1 --> operates throughh rows 
# axis 2 --> operates throughh columns 

arr = np.array([[[1,2,3], [4,5,6]],
               [[5,6,7], [8,9,10]]])


# print(arr[:, :, :2])
arr[1, 1, 2] = 70
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 70]]]
