## Broadcasting: Scaling Arrays without Extra Memory

###### Broadcasting with Arrays of Different Shapes

In [2]:
import numpy as np

arr = np.array([10,20,30,40])

result = arr + 3
result

array([13, 23, 33, 43])

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

result = arr1 + arr2
print(result)

[ 6  8 10 12]


In [8]:
arr1 = np.array([[1,2,3,4], [10,20,30,40]])
arr2 = np.array([5,6,7,8])

result = arr1 + arr2
print(result)
print(result.ndim)

[[ 6  8 10 12]
 [15 26 37 48]]
2
