## Built in Mathematical Functions in NumPy

###### 1. np.mean()

In [1]:
# The mean is simply the average value of numbers:     formula -->  mean = sum of all values / number of total values.
import numpy as np

arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr.mean())


4.5


In [2]:
print(np.mean(arr, axis=0)) # axis=0 --> column wise mean   # (1+5)/2 , (2+6)/2 , (3+7)/2 , (4+8)/2 --> mean
print(np.mean(arr, axis=1)) # axis=1 --> row wise mean   # (1+2+3+4)/4 , (5+6+7+8)/4 --> mean

[3. 4. 5. 6.]
[2.5 6.5]


###### 2. np.std   (Standard Deviation)

In [3]:
# std tells you how spread out the data is from the mean.
# .. small std --> values are close to the mean
# .. large std --> values are spread far from the mean

import numpy as np

arr = np.array([[10,20,30],
               [12,13,14]])

print(arr.std())

6.776183783418707


In [4]:
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

[1.  3.5 8. ]
[8.16496581 0.81649658]


###### 3. np.var() --> Variance

In [5]:
# Variance is basically (standard deviation squared)

import numpy as np

arr = np.array([[10,20,30],
               [40,50,60]])

print(arr.var())

291.6666666666667


###### 4. np.sum()

In [6]:
# It simply adds up all the elements in an array.
import numpy as np

arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr.sum())

36


In [7]:
print(np.sum(arr, axis=0))   # column wise 
print(np.sum(arr, axis=1))   # row wise

[ 6  8 10 12]
[10 26]


###### 5. np.min()  and np.max()

In [8]:
#np.min() → gives the smallest value in the array.
# np.max() → gives the largest value in the array.

import numpy as np

arr = np.array([[1,2,3,4,5],
               [10,20,30,40,50]])

print(arr.min())
print(arr.max())


1
50


In [9]:
print(np.min(arr,axis=0))
print(np.max(arr,axis=1))

[1 2 3 4 5]
[ 5 50]


###### 6. np.prod()

In [10]:
# It multiplies all elements in the array and returns the product.
import numpy as np

arr = np.array([[1,2,3],
               [4,5,6]])

print(arr.prod())     #   1*2*3*4*5*6  --> 720

720


In [11]:
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))

[ 4 10 18]
[  6 120]


###### 7. np.median()

In [12]:
# What is median????

# The median is the number that is exactly in the middle of a list of numbers that has
# been put in order from smallest to largest..
# ....................................
# How to find the median????
# . For an odd number of values --> the median is the single number directly in the middle of list.
# . For an even number of values --> the median is the average (mean) of two numbers in the middle of list.

# ................................................

import numpy as np

arr = np.array([[1,2,3,4],
               [10,20,30,40]])

print(f"Median of all numbers: {np.median(arr)}")   # middle nums are even (4,10) so: median --> 4+10/2 = 7 

Median of all numbers: 7.0


In [13]:
print(np.median(arr,axis=0))
print(np.median(arr,axis=1))

[ 5.5 11.  16.5 22. ]
[ 2.5 25. ]


###### 8. np.percentile()

In [14]:
# A percentile tells the value below which a certain percentage of data falls.
 # Example ::: If your score is at the 90th percentile it means 90% of students scored less than you...

import numpy as np

student_score = np.array([12,67,88,90,89])
print(np.percentile(student_score,10))  # it means 10% of people scored less than 34, and 90% scored above 34...

34.0


In [15]:
P90 = np.percentile(student_score,90)
print(f"90th percentile: {P90} --> 90% of students scored less than {P90} and the top 10% scored above {P90}.")

90th percentile: 89.6 --> 90% of students scored less than 89.6 and the top 10% scored above 89.6.


###### 9. np.argmin()

In [16]:
# Argmin() gives you the index of the minimun value in the array

import numpy as np

arr = np.array([[10,20,30,40,50],
               [9,12,13,14,90]])

print(f"Minimum value index: {np.argmin(arr)}")    # means --> minimum value is 9 at index 5

Minimum value index: 5


###### 10. argmax()

In [17]:
# Argmin() gives you the index of the minimun value in the array

import numpy as np

arr = np.array([[12,13,14,90],
               [91,92,93,60]])

print(f"Maximum value index: {np.argmax(arr)}")   # max is 93 at the index 6

Maximum value index: 6


###### 11. corrcoef()   -->  Correlation coefficient

In [18]:
# What is corrcoef() ??
# It tells you the how strongly two things are related and whether the relationship is positive or negativs?

# . If correlation = +1 (positive) --> whenever one goes up other also goes up perfectly...
# . If correlation = -1 (negative) --> whenever one goes up other goes down perfectly...

# The function correcoef() gives a correlation matrix : [[(x,x) (x,y) ]
#                                                        [ (y,x) (y,y) ]]

import numpy as np

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

# Perfect positive relation..........
print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


In [19]:
z = np.array([10,20,12,11,90])
# Perfect negative relation..........
print(np.corrcoef(y,z))

[[1.         0.69100496]
 [0.69100496 1.        ]]


###### 12. np.unique()  --> Uniqe elements

In [20]:
# It returns the unique (non-duplicate) values from an array

import numpy as np

arr = np.array([[1,2,3,4,5,6],
               [1,20,30,6,5,3]])

print(np.unique(arr))

[ 1  2  3  4  5  6 20 30]


###### 13. np.cumsum() --> Cumulative sum

In [21]:
# It adds the numbers step by step and gives you all the running totals instead of just one final sum...

import numpy as np

arr = np.array([10,20,30,40])

print(arr.cumsum())   # first element (10) then (10+20) then (10+20+30) and so on...

[ 10  30  60 100]


In [22]:
# cumcum with 2D:::
arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(np.cumsum(arr,axis=0))  
print(np.cumsum(arr,axis=1))

[[ 1  2  3  4]
 [ 6  8 10 12]]
[[ 1  3  6 10]
 [ 5 11 18 26]]


###### 14. np.diff()  --> difference

In [23]:
# It tells how much step-by-step change is happening in an array.....
import numpy as np

arr = np.array([10,20,30,15,12])

print(np.diff(arr))

[ 10  10 -15  -3]


In [24]:
# np.diff() with 2D::::

arr = np.array([[12,13,14],
               [10,20,30]])

print(np.diff(arr,axis=1))
print(np.diff(arr,axis=0))


[[ 1  1]
 [10 10]]
[[-2  7 16]]


###### 15. np.linspace() --> linspace(start,stop,num)

In [25]:
# It creates an array with evenly spaced numbers....

import numpy as np

arr1 = np.linspace(0, 18, 5)  # start from (0) stop at (18) and give me evenly spaced (5) numbers..
print(arr)

# ..............

arr2, step = np.linspace(1, 25, 10, retstep=True)    # restep=True will show the spacing (step size)
print(f"Array: {arr2}")
print(f"Step: {step}")

[[12 13 14]
 [10 20 30]]
Array: [ 1.          3.66666667  6.33333333  9.         11.66666667 14.33333333
 17.         19.66666667 22.33333333 25.        ]
Step: 2.6666666666666665


###### 16. np.log()  --> logarithm

In [26]:
# What is log?
# The power to which a base number must be raised to get another number..
# A logarithm reverses this by asking: "What power do you need to raise 10 to in order to get 100?"
# The power of natural log is --> ln(x) = e = 2.718

import numpy as np

arr = np.array([10,100,1000,20])

print(np.log(arr))

[2.30258509 4.60517019 6.90775528 2.99573227]


###### 17. np.exp()  --> exponential of an array

In [27]:
# exp grows a number very fast ---> if i do exp of np.exp(5) it will be like this --> 2.718 and it's power 5 

# and if I want the number back in compressed form I'll go with log()

import numpy as np

x = 10

print(np.exp(x))
print(np.log(np.exp(x)))

22026.465794806718
10.0
